---
# tasks file for /home/student/ansible/roles/apache
- name: Install Package
  yum:
          name: 
            - httpd
            - firewalld  
          state: latest
- name: Start the services
  service: 
          name: "{{ item }}"
          state: started
          enabled: yes
  loop: "{{ [ 'httpd', 'firewalld' ] }}"
- name: Add httpd service in firewalld
  firewalld:
          service: http
          state: enabled
          permanent: yes
          immediate: yes
- name: Copy templete
  template:
          src: template.j2
          dest: /var/www/html/index.html
          
      
