---
# tasks file for HA Proxy balancer
#- name: forward port 80 to other Server
#  firewalld:
#    rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-addr=192.168.123.13 to-port=80
#    state: disabled
#    permanent: yes
#    immediate: yes
#
- name: Install HA Proxy
  yum:
    name: haproxy
    state: present
- name: Copy config file
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    mode: 0644
    owner: root
    group: root
- name: Enable the HA Proxy service
  service:
    name: haproxy
    state: restarted #started
    enabled: yes
- name: open https service in firewall
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes

